# Generated by Django 5.2 on 2025-12-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_messurements',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
