# Generated by Django 5.2 on 2025-12-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_customuser_has_messurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_messurements',
            field=models.BooleanField(default=False),
        ),
    ]
