# Generated by Django 5.2 on 2025-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_customuser_has_messurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cancels',
            field=models.IntegerField(default=0),
        ),
    ]
