# Generated by Django 5.2 on 2026-01-17 05:55

import django.db.models.deletion
import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attire_name', models.CharField(max_length=255)),
                ('attire_type', models.CharField(max_length=255)),
                ('attire_description', models.TextField()),
                ('to_show', models.BooleanField(default=True)),
                ('landing_page', models.BooleanField(default=False)),
                ('total_price', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=gallery.models.attire_image_upload_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=gallery.models.attire_image_upload_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=gallery.models.attire_image_upload_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=gallery.models.attire_image_upload_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=gallery.models.attire_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
