# Generated by Django 5.2 on 2026-01-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attire',
            name='total_price',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
