# Generated by Django 5.2 on 2025-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attire',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
