# Generated by Django 5.2 on 2025-09-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
    ]
