# Generated by Django 5.2 on 2025-10-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_delete_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='facebook_link',
        ),
    ]
