# Generated by Django 5.2 on 2025-11-04 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], default='pending', max_length=20)),
                ('client_response', models.CharField(choices=[('none', 'None'), ('agreed', 'Agreed'), ('disagreed', 'Disagreed')], default='none', max_length=20)),
                ('client_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
