# Generated by Django 5.2 on 2025-11-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_followupappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupappointment',
            name='project_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
