# Generated by Django 5.2 on 2025-11-04 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_followupappointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
