# Generated by Django 5.2 on 2025-11-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_followupappointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupappointment',
            name='admin_note',
            field=models.CharField(blank=True, null=True),
        ),
    ]
