# Generated by Django 5.2 on 2025-11-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_followupappointment_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupappointment',
            name='for_fitting',
            field=models.BooleanField(default=False),
        ),
    ]
