# Generated by Django 5.2 on 2025-11-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_followupappointment_for_fitting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
