# Generated by Django 5.2 on 2025-11-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupappointment',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
