# Generated by Django 5.2 on 2025-11-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_followupappointment_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('fitting', 'Fitting'), ('inquiry', 'Inquiry')], default='inquiry', max_length=20),
        ),
    ]
