# Generated by Django 5.2 on 2025-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='not_come',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
