# Generated by Django 5.2 on 2025-12-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_appointment_not_come'),
        ('gallery', '0002_attire_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attire_from_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='gallery.attire'),
        ),
    ]
