# Generated by Django 5.2 on 2025-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupappointment',
            name='has_messurements',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
