# Generated by Django 5.2 on 2025-12-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_followupappointment_has_messurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupappointment',
            name='has_messurements',
        ),
    ]
