# Generated by Django 5.2 on 2025-12-08 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('chest', models.CharField(blank=True, max_length=50, null=True)),
                ('waist', models.CharField(blank=True, max_length=50, null=True)),
                ('hips', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_width', models.CharField(blank=True, max_length=50, null=True)),
                ('arm_length', models.CharField(blank=True, max_length=50, null=True)),
                ('leg_length', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
