# Generated by Django 5.2 on 2025-06-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('slot_one', models.BooleanField(default=False)),
                ('slot_two', models.BooleanField(default=False)),
                ('slot_three', models.BooleanField(default=False)),
                ('slot_four', models.BooleanField(default=False)),
                ('slot_five', models.BooleanField(default=False)),
            ],
        ),
    ]
