# Generated by Django 5.2 on 2025-12-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailability',
            name='reason_five',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='reason_four',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='reason_one',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='reason_three',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='reason_two',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
