# Generated by Django 5.2 on 2025-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_unavailability_reason_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailability',
            name='reason_five',
            field=models.CharField(blank=True, default='Designer not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='reason_four',
            field=models.CharField(blank=True, default='Designer not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='reason_one',
            field=models.CharField(blank=True, default='Designer not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='reason_three',
            field=models.CharField(blank=True, default='Designer not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='reason_two',
            field=models.CharField(blank=True, default='Designer not available', max_length=255, null=True),
        ),
    ]
