# Generated by Django 5.2 on 2025-12-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0005_alter_unavailability_reason_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailability',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
