# Generated by Django 5.2 on 2025-12-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0006_unavailability_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailability',
            old_name='is_archived',
            new_name='is_archived_five',
        ),
        migrations.AddField(
            model_name='unavailability',
            name='is_archived_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='is_archived_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='is_archived_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='is_archived_two',
            field=models.BooleanField(default=False),
        ),
    ]
