# Generated by Django 5.2 on 2025-12-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0007_rename_is_archived_unavailability_is_archived_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailability',
            name='is_archived_five',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='is_archived_four',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='is_archived_one',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='is_archived_three',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='is_archived_two',
        ),
    ]
