# Generated by Django 5.2 on 2025-09-12 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0003_delete_design'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attire_type', models.CharField(max_length=100)),
                ('targeted_date', models.DateField()),
                ('process_status', models.CharField(choices=[('designing', 'Designing'), ('materializing', 'Materializing'), ('ready', 'Ready'), ('done', 'Done')], default='designing', max_length=20)),
                ('payment_status', models.CharField(choices=[('no_payment', 'No Payment'), ('partial_payment', 'Partial Payment'), ('fully_paid', 'Fully Paid')], default='no_payment', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='appointment.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
