# Generated by Django 5.2 on 2025-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='design_references/'),
        ),
    ]
