# Generated by Django 5.2 on 2025-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0002_design_description_design_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='updates',
            field=models.JSONField(blank=True, default=list, help_text='List of updates or progress logs related to this design. Each entry includes message, image, and process status.'),
        ),
    ]
