# Generated by Django 5.2 on 2025-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0003_design_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance = total_amount - amount_paid.', max_digits=10),
        ),
        migrations.AddField(
            model_name='design',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the gown or design project.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid by the client so far.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='updates',
            field=models.JSONField(blank=True, default=list, help_text='List of updates or progress logs related to this design. Each entry includes: message, process_status, payment_status, amount_paid, added_payment, balance, image, and timestamp.'),
        ),
    ]
