# Generated by Django 5.2 on 2025-10-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0004_design_balance_design_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='reference_image',
        ),
    ]
