# Generated by Django 5.2 on 2025-11-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0005_remove_design_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='updates',
            field=models.JSONField(blank=True, default=list, help_text='List of updates or progress logs related to this design.'),
        ),
    ]
