# Generated by Django 5.2 on 2025-11-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0006_alter_design_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='fitting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
