# Generated by Django 5.2 on 2025-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0007_design_fitting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='fitting_successful',
            field=models.BooleanField(default=False),
        ),
    ]
