# Generated by Django 5.2 on 2025-11-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0008_design_fitting_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='fitting_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
