# Generated by Django 5.2 on 2025-12-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_management', '0009_design_fitting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='process_status',
            field=models.CharField(choices=[('concept', 'Concept'), ('sketching', 'Sketching'), ('designing', 'Designing'), ('material_selection', 'Material Selection'), ('pattern_making', 'Pattern Making'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('materializing', 'Materializing'), ('fitting', 'Fitting'), ('alterations', 'Alterations'), ('final_fitting', 'Final Fitting'), ('ready', 'Ready'), ('picked_up', 'Picked up'), ('done', 'Done')], default='designing', max_length=20),
        ),
    ]
