# Generated by Django 5.2 on 2025-12-08 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_remove_followupappointment_has_messurements'),
        ('design_management', '0010_alter_design_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design', to='appointment.appointment'),
        ),
    ]
