# Generated by Django 5.2 on 2025-11-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_from_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
